server:
  port: 9003
  spring:
    application:
      name: "user"
      cloud:
        function:
          definition: update-communication
          stream:
            bindings:
              update-communication-in-0:
                destination: communication-sent
                group: ${spring.application.name}
                sendCommunication-out-0:
                  destination: send-communication
                  kafka:
                  binder:
                  brokers: -localhost:9092


