  name: build and deploy spring-api
  on:
    push:
      branches:
        - master
 
  jobs:
    build-deploy:
      name: build and deploy spring-api
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3
 
        - name: setup jdk 17
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 17
        - name: build the app
          run: |
            cd user
            mvn clean package --file pom.xml -B
            
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for multi-platform support (optional but recommended)
 
        
 
        - name: Build the Docker image
          run: |
            cd user
            docker build -t my-app .  # Build your Docker image, replace `my-app` with your image name
 
        - name: Run the Docker container
          run: |
            cd user
            docker run -d -p 8080:8080 --name my-spring-app my-app  # Run the container from the image you just built
        - name: Verify the container is running
          run: |
            docker ps  # This will show the running containers, ensuring the container started properly

        - name: Test the app
          run: |
            curl http://localhost:8080
 
 
